nodes: 1
tasks_per_node: 1
tag: AD_alltrainscans_nomeaninten_k400only
eval_suffix: test_ood_old_pp
use_latest: true
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /media/backup_16TB/sean/Monai/Metadata/6_1_2026/train_allscans_valtest_baseline__AD_CN_train_split.csv
  dataset_val: /media/backup_16TB/sean/Monai/Metadata/Oasis3/OASIS3_files_with_diag_unique_subject.csv
  dataset_type: mridataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 1
  num_workers: 16
  num_views_per_segment: 1
  frame_step: 4

optimization:
  attend_across_segments: false
  num_epochs: 300
  resolution: 224
  batch_size: 18
  weight_decay: 0.0025
  lr: 0.00025
  start_lr: 0.00025
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1
  - 1
  random_resize_scale:
  - 0.7
  - 1.0
  reprob: 0.0
  normalize:
  - - 0.146689
    - 0.146689
    - 0.146689
  - - 0.267249
    - 0.267249
    - 0.267249
pretrain:
  model_name: vit_base
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /media/backup_16TB/sean/VJEPA_results/base/
  checkpoint: K400_base_100epoch-latest.pth.tar 
  write_tag: AD_alltrainscans_nomeaninten_k400only
  strategy: AD
logging:
  project: voxel-jepa-ad-bin-base-final # Don't change this
  run_name: AD_alltrainscans_nomeaninten_k400only  # Please change every time before running, this is the name for wandb run file
port: 42005
app: gram_anchoring
  ##todo run tomorrow 9th april.
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_AD_binclass_slice48_mp4/vitl16_brainslice48_ADbinclassifier_lr_half_fix10.yaml --devices cuda:0>/media/backup_16TB/sean/VJEPA/a6000_output/pretrain_maskfix1_tiny/video_classification_frozen/vit_tiny_brainslice48_ADbinclass/lr_half_fix10.log 2>&1
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/vit_base/22_9/AD_bin/entropy_loss/AD_FTPT_halfmask_no_entropy.yaml --devices cuda:2 --validation True --plotter csv
  #python -m evals.main --fname /media/backup_16TB/sean/VoxelJEPA/jepa/configs/evals_a6000/vit_base/AD_bin_eval/mean_loss/12_1_meanintensity_k400_oasis.yaml --devices cuda:1 --validation True --plotter csv

  