nodes: 1
tasks_per_node: 1
tag: vit_tiny_mriload_k400100_non_zoom_100ep # checkpoint
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000_csv/eval_AD/AD_binary_train_alldata_nii_non_zoom_coronal_only.csv
  dataset_val: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000_csv/eval_AD/AD_binary_test_alldata_nii_non_zoom_coronal_only.csv
  dataset_type: mridataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 1
  num_workers: 16
  num_views_per_segment: 1
  frame_step: 4
optimization:
  attend_across_segments: false
  num_epochs: 100
  resolution: 224
  batch_size: 20
  weight_decay: 0.01
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1
  - 1
  random_resize_scale:
  - 1
  - 1
  reprob: 0.0
  normalize:
  - - 0.146689
    - 0.146689
    - 0.146689
  - - 0.267249
    - 0.267249
    - 0.267249
pretrain:
  model_name: vit_tiny
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /media/backup_16TB/sean/VJEPA/a6000_output/vit_tiny/K400/scratch
  checkpoint: pass # name of pretrained model file inside folder
  write_tag: mriloader_scratch_mlp
  strategy: skip_1

logging:
  project: voxel-jepa-ad-bin-tiny-scratch # Don't change this
  run_name: mriloader_scratch_mlp # Please change every time before running, this is the name for wandb run file
port: 42005
  ##todo run tomorrow 9th april.
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_AD_binclass_slice48_mp4/vitl16_brainslice48_ADbinclassifier_lr_half_fix10.yaml --devices cuda:0>/media/backup_16TB/sean/VJEPA/a6000_output/pretrain_maskfix1_tiny/video_classification_frozen/vit_tiny_brainslice48_ADbinclass/lr_half_fix10.log 2>&1
  #python -m app_scratch_mlp.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/scratch/scratch_taken_from_evals/scratch_tiny_debug.yaml --devices cuda:2 --plotter csv
  