nodes: 1
tasks_per_node: 1
tag: MCINC_alltrainscans_03_std_06_mean_diag
eval_suffix: val_last
use_latest: true
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /media/backup_16TB/sean/Monai/Metadata/6_1_2026/A_MCI_CN_allscantrain_split.csv
  dataset_val: /media/backup_16TB/sean/Monai/Metadata/6_1_2026/A_MCI_CN_allscanval_split.csv
  dataset_type: mridataset_v2
  num_classes: 2
  frames_per_clip: 16
  num_segments: 1
  num_workers: 4
  num_views_per_segment: 1
  frame_step: 4

optimization:
  attend_across_segments: false
  num_epochs: 300
  resolution: 224
  batch_size: 18
  weight_decay: 0.0025
  lr: 0.00025
  start_lr: 0.00025
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1
  - 1
  random_resize_scale:
  - 0.7
  - 1.0
  reprob: 0.0
  normalize:
  - - 0.146689
    - 0.146689
    - 0.146689
  - - 0.267249
    - 0.267249
    - 0.267249
pretrain:
  model_name: vit_base
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /media/backup_16TB/sean/VJEPA_results/base/
  checkpoint: decode_splice_no_ent_9_1_mean_0_6std_div_0_3_diag-latest.pth.tar
  write_tag: MCINC_alltrainscans_03_std_06_mean_diag
  strategy: AD
logging:
  project: voxel-jepa-mci-cn-base-final # Don't change this
  run_name: MCINC_alltrainscans_03_std_06_mean_diag  # Please change every time before running, this is the name for wandb run file
port: 42005
app: gram_anchoring

  #python -m evals.main --fname /media/backup_16TB/sean/VoxelJEPA/jepa/configs/evals_a6000/vit_base/MCI_CN/combin_loss/12_1_0_3std_0_6_mean_diag.yaml --devices cuda:2 --validation True --plotter csv

  